### ISSUE TITLE
Missing binding.gyp for auth/backend/deps/unixlib

### ISSUE THREAD

**Issue by atweiden** [remotestorage/rs-serve#5]
_[rs-serve-git PKGBUILD](https://github.com/atweiden/pkgbuilds/tree/master/rs-serve-git)_

Build expects but doesn't find binding.gyp in auth/backend/deps/unixlib. Can't make bindings for authorization server.

``` bash
[DEPS] unixlib
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.10
gyp info using node@0.10.19 | linux | x64
gyp info spawn python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/Projects/atweiden/pkgbuilds/rs-serve-git/src/rs-serve/auth/backend/deps/unixlib/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.node-gyp/0.10.19/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.node-gyp/0.10.19',
gyp info spawn args   '-Dmodule_root_dir=/home/user/Projects/atweiden/pkgbuilds/rs-serve-git/src/rs-serve/auth/backend/deps/unixlib',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home/user/Projects/atweiden/pkgbuilds/rs-serve-git/src/rs-serve/auth/backend/deps/unixlib) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.11.2-1-ARCH
gyp ERR! command "node" "/bin/node-gyp" "configure"
gyp ERR! cwd /home/user/Projects/atweiden/pkgbuilds/rs-serve-git/src/rs-serve/auth/backend/deps/unixlib
gyp ERR! node -v v0.10.19
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
make: *** [bindings] Error 1
```

**Comment by sebn** [comment]
@atweiden it's a git submodule.

Try running `git submodule update --init` before building.
